# Generated by Django 5.2.8 on 2025-11-27 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FashionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Look",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("haut", models.CharField(max_length=200)),
                ("bas", models.CharField(max_length=200)),
                ("chaussures", models.CharField(max_length=200)),
                ("accessoires", models.TextField()),
                ("justification", models.TextField()),
                ("prix_total", models.FloatField(default=0.0)),
                ("image_url", models.URLField(blank=True, null=True)),
                (
                    "fashion_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="looks",
                        to="fashion.fashionrequest",
                    ),
                ),
            ],
        ),
    ]
