# Generated by Django 5.2.8 on 2025-11-26 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FashionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_input", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("raw_response", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Look",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("top", models.TextField()),
                ("bottom", models.TextField()),
                ("shoes", models.TextField()),
                ("accessories", models.TextField()),
                ("justification", models.TextField()),
                ("style_score", models.DecimalField(decimal_places=1, max_digits=3)),
                (
                    "budget_rank",
                    models.PositiveIntegerField(
                        help_text="1 = le plus accessible, 3 = le plus premium"
                    ),
                ),
                ("budget_label", models.CharField(default="equilibré", max_length=50)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fashion_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="looks",
                        to="wardrobe.fashionrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["budget_rank", "created_at"],
            },
        ),
    ]
